services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "be-pura"
    container_name: puraapp
    environment:
      - NODE_ENV=${NODE_ENV} # development or production
    volumes:
      - ./:/home/node/app
    restart: always
    command: sh -c 'npm install && node sync &&  npm run start '
    depends_on:
      - db
    ports:
      - 3000:3000
    # command: sh -c 'npm install && npx sequelize-cli db:migrate && if [ "$NODE_ENV" = "development" ]; then npm run start; else pm2-runtime bin/www; fi'
  db:
    image: postgres:16
    container_name: pura
    ports:
      - 5001:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGPORT: 5432
      TZ: Asia/Jakarta